# Generated by Django 4.2.16 on 2026-08-25 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('provider', models.CharField(default='generic', max_length=50)),
                ('encrypted_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'git_credentials',
            },
        ),
        migrations.CreateModel(
            name='RepositoryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.CharField(max_length=500)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('cloning', 'Cloning'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositories.gitcredential')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_imports', to='projects.project')),
            ],
            options={
                'db_table': 'repository_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
