# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="weekly_scan_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="ci_token_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="ci_token_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="ci_token_prefix",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
