# Generated by Django 4.2.16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_owners(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectMembership = apps.get_model("projects", "ProjectMembership")
    for project in Project.objects.all():
        ProjectMembership.objects.get_or_create(
            project=project,
            user_id=project.owner_id,
            defaults={"role": "owner"},
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_ci_weekly_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Project admin"),
                            ("analyst", "Analyst"),
                            ("developer", "Developer"),
                        ],
                        default="developer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_project_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_memberships",
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProjectInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Project admin"),
                            ("analyst", "Analyst"),
                            ("developer", "Developer"),
                        ],
                        default="developer",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True)),
                ("accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_invites",
            },
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(fields=["user", "role"], name="project_mem_user_id_role_idx"),
        ),
        migrations.AddIndex(
            model_name="projectinvite",
            index=models.Index(fields=["token"], name="project_inv_token_idx"),
        ),
        migrations.AddIndex(
            model_name="projectinvite",
            index=models.Index(fields=["email"], name="project_inv_email_idx"),
        ),
        migrations.RunPython(backfill_owners, migrations.RunPython.noop),
    ]
