# Generated by Django 4.2.16 on 2026-08-25 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=1000)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('masked_value', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_findings', to='projects.project')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_findings', to='scanner.scan')),
            ],
            options={
                'db_table': 'secret_findings',
                'indexes': [models.Index(fields=['project', 'status'], name='secret_find_project_d128b5_idx'), models.Index(fields=['fingerprint'], name='secret_find_fingerp_950836_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=50)),
                ('rule_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('scanner_severity', models.CharField(blank=True, max_length=20)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('category', models.CharField(choices=[('injection', 'Injection'), ('xss', 'Cross-Site Scripting'), ('authentication', 'Authentication'), ('access_control', 'Access Control'), ('cryptography', 'Cryptography'), ('secrets', 'Secrets Exposure'), ('vulnerable_dependency', 'Vulnerable Dependency'), ('insecure_configuration', 'Insecure Configuration'), ('infrastructure_as_code', 'Infrastructure as Code'), ('container_security', 'Container Security'), ('deserialization', 'Insecure Deserialization'), ('ssrf', 'Server-Side Request Forgery'), ('path_traversal', 'Path Traversal'), ('information_disclosure', 'Information Disclosure'), ('other', 'Other')], default='other', max_length=50)),
                ('cwe', models.CharField(blank=True, max_length=20)),
                ('owasp_category', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('line_start', models.PositiveIntegerField(blank=True, null=True)),
                ('line_end', models.PositiveIntegerField(blank=True, null=True)),
                ('column_start', models.PositiveIntegerField(blank=True, null=True)),
                ('column_end', models.PositiveIntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects.project')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'findings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='findings_project_76e75f_idx'), models.Index(fields=['scan', 'severity'], name='findings_scan_id_8f361b_idx'), models.Index(fields=['fingerprint'], name='findings_fingerp_038764_idx'), models.Index(fields=['category'], name='findings_categor_5fd8a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('ecosystem', models.CharField(max_length=50)),
                ('manifest_file', models.CharField(max_length=500)),
                ('vulnerability_id', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('fixed_version', models.CharField(blank=True, max_length=100)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.project')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='scanner.scan')),
            ],
            options={
                'db_table': 'dependencies',
                'indexes': [models.Index(fields=['project', 'severity'], name='dependencie_project_2b0f8c_idx'), models.Index(fields=['package_name', 'ecosystem'], name='dependencie_package_78f107_idx')],
            },
        ),
    ]
