# Generated by Django 4.2.16 on 2026-08-25 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('sast', 'SAST Only'), ('sca', 'SCA Only'), ('secrets', 'Secrets Only'), ('iac', 'IaC Only'), ('container', 'Container Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('progress_stage', models.CharField(blank=True, max_length=100)),
                ('enabled_scanners', models.JSONField(blank=True, default=dict)),
                ('severity_threshold', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_findings', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('security_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('skipped_unavailable', 'Skipped (unavailable)'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=30)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('output_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_runs', to='scanner.scan')),
            ],
            options={
                'db_table': 'scanner_runs',
                'indexes': [models.Index(fields=['scan', 'scanner_name'], name='scanner_run_scan_id_f70423_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['project', 'status'], name='scans_project_87007c_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['created_at'], name='scans_created_363150_idx'),
        ),
    ]
