# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="trigger_source",
            field=models.CharField(
                choices=[
                    ("ui", "UI"),
                    ("ci", "CI"),
                    ("webhook", "Webhook"),
                    ("scheduled", "Scheduled"),
                ],
                default="ui",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="git_sha",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
