# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_trigger_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="scope_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
