"""Catalog of authorized assessment modes. Live checks stay scoped to owned assets."""

MODES = [
    {
        "id": "black_box",
        "name": "Black box",
        "receives": "Only target/scope",
        "testing": "External reconnaissance, web/API surface, exposed service banners from headers",
        "inputs": ["url"],
        "requires_ownership": True,
        "live": True,
    },
    {
        "id": "gray_box",
        "name": "Gray box",
        "receives": "Limited credentials/information",
        "testing": "Authenticated application and API checks with a token you supply",
        "inputs": ["url", "bearer_token"],
        "requires_ownership": True,
        "live": True,
    },
    {
        "id": "white_box",
        "name": "White box",
        "receives": "Source code/configuration",
        "testing": "SAST-style patterns, secrets, dependency and IaC hints in pasted source",
        "inputs": ["source"],
        "requires_ownership": False,
        "live": False,
    },
    {
        "id": "penetration_testing",
        "name": "Penetration testing",
        "receives": "Authorized target + defined scope",
        "testing": "Controlled security validation (passive checks + engagement checklist)",
        "inputs": ["url", "scope_notes"],
        "requires_ownership": True,
        "live": True,
    },
    {
        "id": "web",
        "name": "Web testing",
        "receives": "Website/API",
        "testing": "OWASP-style baseline: HTTPS, cookies, security headers",
        "inputs": ["url"],
        "requires_ownership": True,
        "live": True,
    },
    {
        "id": "mobile",
        "name": "Mobile testing",
        "receives": "APK/IPA + test environment",
        "testing": "Static packaging review: manifests, embedded URLs, secret-like strings",
        "inputs": ["package"],
        "requires_ownership": False,
        "live": False,
    },
    {
        "id": "network",
        "name": "Network testing",
        "receives": "Authorized network",
        "testing": "This host’s listening ports, DNS, and IP classification (no third-party port scans)",
        "inputs": ["host"],
        "requires_ownership": False,
        "live": True,
    },
    {
        "id": "cloud",
        "name": "Cloud testing",
        "receives": "Authorized cloud configuration",
        "testing": "IAM, storage, and network configuration review from JSON you paste",
        "inputs": ["config_text"],
        "requires_ownership": False,
        "live": False,
    },
    {
        "id": "container",
        "name": "Container testing",
        "receives": "Images/configuration",
        "testing": "Dockerfile, Compose, and Kubernetes snippets: tags, user, secrets",
        "inputs": ["config_text"],
        "requires_ownership": False,
        "live": False,
    },
    {
        "id": "api",
        "name": "API testing",
        "receives": "API specification/endpoints",
        "testing": "OpenAPI auth, public paths, HTTP vs HTTPS servers, input validation hints",
        "inputs": ["spec_text"],
        "requires_ownership": False,
        "live": False,
    },
    {
        "id": "code_security",
        "name": "Code security",
        "receives": "Repository/source",
        "testing": "SAST, SCA, secrets, dependency and IaC analysis (paste here or use Projects)",
        "inputs": ["source"],
        "requires_ownership": False,
        "live": False,
    },
]

MODE_MAP = {row["id"]: row for row in MODES}
